name: dependencies
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  fluttertoast: ^8.0.7

  # Core
  flutter_bloc: ^6.1.3
  dio: ^3.0.10
  http: ^0.12.0
  shared_preferences: ^2.0.6
  equatable: ^2.0.2
  get_it: ^7.1.3



  #json_serializable: ^3.5.1
  #build_runner: ^1.11.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  #json_annotation: ^3.1.1



flutter: