name: core
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^5.0.1

  # This is our modular
  dependencies:
    path: ../dependencies
  shared:
    path: ../shared


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  #json_serializable: ^3.5.1
  #json_annotation: ^3.1.1
  #build_runner: ^2.1.2



flutter: